### ISSUE TITLE
HS-Docs checklist

### ISSUE THREAD

**Issue by ViniBGoulart** [HighsoftWeb/hs-docs-web#1]
- [ ] Tipo de Titulo - Hugo - @ViniBGoulart 
- [ ] Nota de Remessa - Vitória 
- [ ] Procedimento nota de Entrega futura - Thaise - @ViniBGoulart
