### ISSUE TITLE
HS-Docs incomplet docs Checklist

### ISSUE THREAD

**Issue by ViniBGoulart** [HighsoftWeb/hs-docs-web#3]
- [ ] HSCorp > Começando > Login
- [ ] docs/consultas/clientes/sem-movimentos/sobre.md > O que são clientes sem movimentos?
- [ ] docs/vendas/nota-de-venda/estorno-venda/sobre.md > Como funciona na Highsoft
- [ ] docs/vendas/nota-de-venda/nota-futura/sobre.md > Como funciona na Highsoft
